### ISSUE TITLE
[request] Display active workspace

### ISSUE THREAD

**Issue by kobel240** [abrasic/blendpresence#11]
the option to display active workspace instead of active mode

**Comment by abrasic** [comment]
Hello! BlendPresence 1.8 will come with new system **Icon Sets**. This is where you can switch from the original **Active Mode** icon set to the new **Active Workspace** icon set.

For the icons to show up, you need to have a workspace active with one of the following names:

- Modeling
- Sculpting
- UV Editing
- Texture Paint
- Shading
- Animation
- Rendering
- Compositing
- Geometry Nodes
- Scripting

As of now, the workspace name must be typed exactly as it's shown above. I'll eventually add more similar terms (ex. detect name "Geo Nodes") to add more flexibility to the system.

<img src="https://i.ibb.co/LrqbCJC/e.png">

**Comment by abrasic** [comment]
Closing for [1.8.0](https://github.com/abrasic/blendpresence/releases/tag/1.8.0). If you encounter any problems with this feature in that version, please let me know. Thanks!

**Comment by Wolfgang-IX** [comment]
is there a way to add custom name to the categories?
for example "Layout" & "Organize" in the same category as Modeling?
