### ISSUE TITLE
Not working with better discord

### ISSUE THREAD

**Issue by joevento** [abrasic/blendpresence#14]
This doesnt seem to work with better discord, is there any change it could be made to work with it?

**Comment by joevento** [comment]
Ok it seems like it was on my end, reinstalled the plugin and now its showing up. :D

**Comment by abrasic** [comment]
Hi @Lamea132,
What Blender & BetterDiscord version are you using? Are you using Discord Stable or Discord Canary? What plugins do you have enabled?

BetterDiscord 1.9.3 (on Discord Stable) appears to be working fine -- im using ~10ish plugins and no theme. Please ensure that you do not have any plugins/themes that could potentially be interfering with how the presence is displayed on Discord (try disabling all your plugins and restart the client (`Ctrl + R`) and see if that works for you.

**Comment by Lamea132** [comment]
> Hi @Lamea132, What Blender & BetterDiscord version are you using? Are you using Discord Stable or Discord Canary? What plugins do you have enabled?
> 
> BetterDiscord 1.9.3 (on Discord Stable) appears to be working fine -- im using ~10ish plugins and no theme. Please ensure that you do not have any plugins/themes that could potentially be interfering with how the presence is displayed on Discord (try disabling all your plugins and restart the client (`Ctrl + R`) and see if that works for you).

I'm actually using Bforartists but it's still Blender 3.5.1 and I'm using the stable version of BetterDiscord 1.9.3. The addons I have in Bforartists should still work like they do in Blender. But I'll try your solution and see if it works

**Comment by Lamea132** [comment]
Alrighty so I tried the fix but it didn't work unfortunately. I'm using a fork of this plugin so I think I would have to go to the issues tab over there.

**Comment by abrasic** [comment]
Never heard of Bforartists but after installing it onto a new install it still seems to show up as normal.

Last couple of things to check:
* Check again to confirm that in Discord, your `User Settings > Activity Privacy > "Display current activity as a status message" is _enabled_. Do note that there is a feature right below it that toggles your activity status automatically for large servers. If it's disabled, try switching to a smaller Discord server to see if its just not showing up for that specific server.
* Change some options inside of BlendPresence's preferences to check if a certain display mode is not compatible with Bforartists.
* Check the Blender console for any possible errors: `Window > Toggle system console`.

**Comment by Lamea132** [comment]
Weird. Tried all of these and all but one didn't work. There's a detail I left out that might solve this problem though. When I disable the addon it gives me this: 
![Screenshot 2023-06-27 154246](https://github.com/abrasic/blendpresence/assets/76811768/8b8e2723-513e-4e57-889a-1103c49df513)

**Comment by abrasic** [comment]
Hi @Lamea132,
I've been able to reproduce your issue. The cause seems to be the use of deprecated function `bpy.app.version_char` which was removed in Blender 4.0 (which I guess is what Bforartists 3.5.1 is based off of???)

I released a hotfix for the current version. You can download it [here](https://github.com/abrasic/blendpresence/releases/tag/1.8.0)

Let me know if that worked for you.

**Comment by Lamea132** [comment]
I got this error when trying to enable it. But I bet this'll solve my problem though:
![image](https://github.com/abrasic/blendpresence/assets/76811768/90e4d2da-9ce7-41b2-a4ea-9f45d233e32b)

**Comment by Lamea132** [comment]
WAIT NEVER MIND I had to close and open up Blender again but it worked! WOO! My mistake lol

**Comment by Lamea132** [comment]
Forgot to say thank you for helping
