### ISSUE TITLE
Add-on doesn't work on Blender 4.0

### ISSUE THREAD

**Issue by BlueF00x** [abrasic/blendpresence#16]
I noticed after using Blender 4.0 the plugin doesn't seem to work anymore? It installs fine but Discord doesn't seem to pick it up.

**Comment by abrasic** [comment]
Hello,
The addon seems to be working as of 4.0.1.

The latest version received 2 hotfixes in the past several months. If you installed the addon before 6/27/23, please make sure that you have the latest [release](https://github.com/abrasic/blendpresence/releases/tag/1.8.0) which includes 4.0 support.

If the latest version does not work still, refer to [Troubleshooting](https://github.com/abrasic/blendpresence#troubleshooting) and provide any console errors, system information and software versions if necessary.

Thanks

**Comment by BlueF00x** [comment]
Hey!

Alright cool! I probably still have the version before 6/27/23. I'll check it out later thanks!
