### ISSUE TITLE
resets discord time

### ISSUE THREAD

**Issue by o0Remake0o** [abrasic/blendpresence#20]
after 24h it resets, could it maybe go like over 24h?

**Comment by abrasic** [comment]
This is a limitation put in place by Discord itself as their Rich Presence functionality does not track days elapsed. Once it reaches 24 hours, it will reset itself back to 0:00:00.

[[1]](https://github.com/angelolz/CookieClickerRPC/issues/2) [[2]](https://github.com/andweeb/presence.nvim/issues/109) [[3]](https://github.com/Jxyme/simple-discord-rpc?tab=readme-ov-file#please-note-discord-currently-limits-the-timestamps-to-a-maximum-of-24-hours-left-or-elapsed)
