### ISSUE TITLE
Error, when i tried to enable the add-on

### ISSUE THREAD

**Issue by VerZnox** [abrasic/blendpresence#6]
![Untitled](https://user-images.githubusercontent.com/51857225/152677828-6316b569-6b25-4c34-bf57-4f41da899cc0.png)

**Comment by abrasic** [comment]
Hi, thanks for the report.

Please try the temporary fix shown in #5 and let me know if that works for you.

**Comment by VerZnox** [comment]
thanks for the fast respond,
it does work for me
after i delete the argument still occur the same erro
![Untitled](https://user-images.githubusercontent.com/51857225/152721643-0e9fdfec-dca7-4626-9cf5-bd46db822e8c.png)
r

**Comment by abrasic** [comment]
Apologies for the issues thus far :( I've been unable to replicate the issue in 2.93 on my end, but try this fix instead:

- If necessary, remove the addon from Blender and close the application.
- Go to line 83 of `pypresence/baseclient.py`
- Set this line to `loop = asyncio.set_event_loop(asyncio.new_event_loop())`
- Re-install the addon

(related: https://stackoverflow.com/questions/60461433/python3-asyncio-there-is-no-current-event-loop-in-thread-when-spawn-a-new-thread)

Let me know if that worked for you

**Comment by VerZnox** [comment]
ok the add-on now work.
maybe ill try to upgrade to 3.0.1
thank you
