### ISSUE TITLE
Display GPU for AMD. pls

### ISSUE THREAD

**Issue by NvgT-e** [abrasic/blendpresence#9]
display GPU do not funciton in grapich card AMD

**Comment by abrasic** [comment]
Hi, thanks for your request.

AMD GPUs are not supported at this time, primarily because I don't own one, I'd rather not add a feature that's impossible to test.

If you'd like to help with me adding this feature, please send me the complete name of your AMD GPU as shown in Blender > Edit > Preferences > System > HIP

**Comment by NvgT-e** [comment]
I'm using a Radeon RX 550, the display could look like this.

Thanks

**Comment by abrasic** [comment]
I added potential support for this in [1.8.0](https://github.com/abrasic/blendpresence/releases/tag/1.8.0). I will leave this issue open until someone with an AMD card can confirm that their card model shows up properly in the presence

**Comment by NvgT-e** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/108752156/184504828-282ee3d5-e6dd-40b9-addf-36913f2a4c2b.png)
![Screenshot_2](https://user-images.githubusercontent.com/108752156/184504830-c5ae9ad4-a549-473f-b6d4-be0e516ae0e8.png)

hello, I went to test this latest version 1.8.0 that you released and it still doesn't show the status of AMD cards.

**Comment by abrasic** [comment]
Hi there, apologies for the trouble.

To better diagnose this problem, I will need your card model that Blender reports back from the console. To get this information, please do the following:

1. Open a Blender project
2. Open a Python Console (or press `Shift + F4`) and paste the following code inside of it:
```
import gpu
gpu.platform.renderer_get()
```
3. Press Enter to execute, and reply back with what it returns in blue text (example below). A screenshot is suggested.

![image](https://user-images.githubusercontent.com/43157991/184510599-6a1bd98f-0122-4c73-855a-0c97cc2a0c66.png)

Thanks for your assistance :)

**Comment by NvgT-e** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/108752156/184733702-0aef57bd-e06d-43af-af77-9fc70a9b1169.png)

**Comment by abrasic** [comment]
I just sent a fix to the main branch, download the repository (Code > Download as ZIP) and let me know if that works for you :)

Thanks

**Comment by NvgT-e** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/108752156/184790486-ff950383-bf82-48d0-9663-8000b0d5d2b6.png)
Perfect! thanks for adding support for AMD cards, it helps the community a lot.
thanks <3

**Comment by abrasic** [comment]
Glad its working for you :) Thanks for your assistance
